# Phoenix MLS Production Configuration
# This file contains Phoenix MLS specific production settings

# Phoenix MLS Scraping Configuration
phoenix_mls:
  # Base URL for Phoenix MLS website
  base_url: "https://www.phoenixmlssearch.com"
  
  # Rate limiting settings
  rate_limit: 60  # requests per hour
  min_request_delay: 3.6  # seconds between requests
  
  # Request settings
  timeout: 30000  # milliseconds
  max_retries: 3
  page_timeout: 30000
  
  # Anti-detection settings
  stealth_mode: true
  respect_robots_txt: true
  randomize_timing: true
  
  # Scraping limits
  max_pages_per_search: 5
  max_properties_per_session: 100
  
  # Session management
  session_rotation_interval: 300  # seconds
  cookie_persistence: true
  
  # Browser configuration
  browser:
    headless: true
    viewport:
      width: 1920
      height: 1080
    args:
      - "--no-sandbox"
      - "--disable-setuid-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-accelerated-2d-canvas"
      - "--no-first-run"
      - "--no-zygote"
      - "--disable-gpu"
  
  # Selectors (update based on actual site structure)
  selectors:
    search_input: "input[name='search']"
    property_listing: ".property-listing"
    property_address: ".property-address"
    property_price: ".property-price"
    property_details: ".property-details"
    property_beds: ".beds"
    property_baths: ".baths"
    property_sqft: ".sqft"
    next_page: ".pagination .next"
    property_link: "a.property-link"
    
  # Error detection patterns
  error_patterns:
    rate_limit: "Too many requests"
    blocked: "Access denied"
    captcha: "Please verify you are human"
    session_expired: "Session has expired"

# Proxy Configuration for Production
proxy_production:
  # Webshare configuration
  webshare:
    enabled: true
    endpoints:
      - "premium-datacenter.webshare.io:8080"
      - "premium-datacenter.webshare.io:8081"
      - "premium-residential.webshare.io:8080"
      - "premium-residential.webshare.io:8081"
    
    # Proxy rotation settings
    rotation:
      enabled: true
      strategy: "round-robin"  # round-robin, random, or performance-based
      health_check_interval: 300  # seconds
      max_consecutive_failures: 3
      min_healthy_proxies: 2
      
    # Performance tracking
    performance:
      track_response_times: true
      prefer_fast_proxies: true
      response_time_threshold: 5.0  # seconds
      
  # Fallback proxy configuration
  fallback:
    enabled: false
    providers: []  # Add backup proxy providers if needed

# Data Quality Settings for Production
data_quality:
  # Validation requirements
  validation:
    require_address: true
    require_price: false  # Price might not always be available
    require_property_type: true
    min_data_completeness: 0.6  # 60% of fields should be populated
    
  # Data normalization
  normalization:
    standardize_addresses: true
    parse_price_ranges: true
    extract_numeric_values: true
    clean_html_tags: true
    
  # Duplicate detection
  deduplication:
    enabled: true
    check_fields:
      - "address"
      - "mls_number"
    similarity_threshold: 0.95

# Performance Optimization
performance_optimization:
  # Caching settings
  caching:
    enabled: true
    cache_search_results: true
    cache_ttl_minutes: 60
    max_cache_size_mb: 100
    
  # Batching configuration
  batching:
    enabled: true
    batch_size: 10
    max_concurrent_pages: 3
    
  # Resource limits
  resource_limits:
    max_memory_usage_mb: 512
    max_cpu_percentage: 80
    gc_threshold: 100

# Monitoring and Alerting
monitoring:
  # Metrics collection
  metrics:
    enabled: true
    track_success_rate: true
    track_response_times: true
    track_proxy_health: true
    track_data_quality: true
    
  # Alerting thresholds
  alerts:
    min_success_rate: 0.95  # 95% success rate
    max_avg_response_time: 5.0  # seconds
    min_healthy_proxies: 2
    max_consecutive_errors: 5
    
  # Logging
  logging:
    log_all_requests: false  # Only log errors in production
    log_response_sizes: true
    sanitize_sensitive_data: true
    
# Error Handling Strategy
error_handling:
  # Retry configuration
  retry:
    max_attempts: 3
    initial_delay: 2.0  # seconds
    backoff_factor: 2.0
    max_delay: 30.0  # seconds
    
  # Error recovery
  recovery:
    proxy_rotation_on_error: true
    session_reset_on_error: true
    cooldown_after_block: 300  # seconds
    
  # Fallback strategies
  fallback:
    use_cached_data: true
    reduce_request_rate: true
    notify_on_critical_errors: true

# Compliance and Legal
compliance:
  # Rate limiting compliance
  respect_rate_limits: true
  user_agent: "Phoenix Real Estate Collector 1.0 (Personal Use; Contact: admin@phoenixre.com)"
  
  # Data privacy
  privacy:
    anonymize_personal_data: true
    exclude_personal_identifiers: true
    comply_with_robots_txt: true
    
  # Usage limits
  limits:
    max_daily_requests: 1000
    max_hourly_requests: 100
    respect_site_guidelines: true