# TDD Guard Configuration for RE-analysis-generator
project_name: "RE-analysis-generator"
enforce_tdd: true
test_first_required: true

# Tracking settings
track_cycles: true
cycle_storage: .claude/tdd-guard/data/cycles.json
test_storage: .claude/tdd-guard/data/test.json

# Coverage requirements
coverage:
  line: 95
  branch: 90
  
# Mutation testing
mutation:
  enabled: true
  minimum_score: 85

# Pre-commit hooks
hooks:
  pre_commit:
    - check_test_first
    - verify_coverage
    - mutation_test