version: '3.8'

services:
  phoenix-real-estate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phoenix-real-estate
    restart: always
    environment:
      - PHOENIX_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    depends_on:
      - mongodb
      - ollama
    networks:
      - phoenix-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:8.1.2
    container_name: phoenix-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-defaultpassword}
      MONGO_INITDB_DATABASE: phoenix_real_estate
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - phoenix-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/phoenix_real_estate --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: phoenix-ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - phoenix-network
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  ollama_data:
    driver: local

networks:
  phoenix-network:
    driver: bridge
