# Development environment configuration

# Override logging for development
logging:
  level: "DEBUG"
  format: "text"
  console_output: true
  file_path: "logs/development.log"

# Development database (local MongoDB or Atlas)
database:
  name: "phoenix_real_estate_dev"
  max_pool_size: 5

# Relaxed collection settings for development
collection:
  max_requests_per_hour: 50  # Lower for development
  min_request_delay: 5.0     # Slower for safety
  
  # Test with single ZIP code
  target_zip_codes:
    - "85031"

# Development data sources
sources:
  maricopa_county:
    enabled: true
    rate_limit: 50  # Conservative for development
    
  phoenix_mls:
    enabled: false  # Disable scraping in development
    
  particle_space:
    enabled: false

# Disable proxy for development
proxy:
  enabled: false

# Development processing
processing:
  llm_model: "llama2:7b"
  batch_size: 5
  max_processing_workers: 1

# Relaxed validation for development
validation:
  strict_mode: false
  max_price: 100000000  # Allow higher for testing

# Performance settings for development
performance:
  enable_caching: true
  cache_ttl_minutes: 10  # Shorter cache for development
  max_memory_usage_mb: 256

# Development error handling
error_handling:
  max_error_rate: 0.5  # Allow more errors in development
  error_cooldown_minutes: 5
  alert_on_consecutive_failures: 10