# Testing environment configuration

# Test logging
logging:
  level: "DEBUG"
  format: "text"
  console_output: false  # Reduce noise in tests
  file_path: null

# Test database
database:
  name: "phoenix_real_estate_test"
  max_pool_size: 2
  min_pool_size: 1

# Minimal collection for testing
collection:
  max_requests_per_hour: 10
  min_request_delay: 1.0
  
  # Single test ZIP code
  target_zip_codes:
    - "85031"

# Disable external services for testing
sources:
  maricopa_county:
    enabled: false
    
  phoenix_mls:
    enabled: false
    
  particle_space:
    enabled: false

# No proxy for testing
proxy:
  enabled: false

# Fast processing for tests
processing:
  llm_model: "mock"  # Use mock LLM for testing
  llm_timeout: 5
  batch_size: 2
  max_processing_workers: 1

# Strict validation for testing
validation:
  strict_mode: true
  require_address: true
  require_price: false

# Minimal performance settings for tests
performance:
  enable_caching: false  # Disable caching for consistent tests
  max_memory_usage_mb: 128

# Sensitive error handling for tests
error_handling:
  max_error_rate: 0.0  # No errors allowed in tests
  error_cooldown_minutes: 1
  alert_on_consecutive_failures: 1