# Alertmanager configuration for Phoenix MLS Scraper
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@phoenix-mls.local'
  smtp_auth_username: 'alerts@phoenix-mls.local'
  smtp_auth_password: 'password'

# Email notification template
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: critical-alerts
      group_wait: 0s
      repeat_interval: 15m
    
    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: warning-alerts
      repeat_interval: 4h
    
    # Info alerts - daily digest
    - match:
        severity: info
      receiver: info-alerts
      repeat_interval: 24h

# Alert receivers
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'engineering-oncall@company.com'
        subject: '🚨 CRITICAL: Phoenix MLS Scraper Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ if .Annotations.recommendation }}
          Recommendation: {{ .Annotations.recommendation }}
          {{ end }}
          {{ if .Annotations.runbook }}
          Runbook: {{ .Annotations.runbook }}
          {{ end }}
          {{ end }}
          
          View in Grafana: http://grafana.local/d/scraper-performance
          
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ if .Annotations.recommendation }}
          💡 *Recommendation:* {{ .Annotations.recommendation }}
          {{ end }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'engineering@company.com'
        subject: '⚠️ WARNING: Phoenix MLS Scraper Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ if .Annotations.recommendation }}
          Recommendation: {{ .Annotations.recommendation }}
          {{ end }}
          {{ end }}
          
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}

  - name: 'info-alerts'
    email_configs:
      - to: 'engineering@company.com'
        subject: 'ℹ️ INFO: Phoenix MLS Scraper Daily Digest'
        body: |
          Daily Alert Digest - {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

# Inhibit rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Don't send session alerts if scraper is down
  - source_match:
      alertname: 'ScraperNotResponding'
    target_match_re:
      alertname: '^(SessionExpired|SessionAgeTooOld)$'