global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "phoenix_alerts.yml"

scrape_configs:
  - job_name: 'phoenix-real-estate'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:27017']
    scrape_interval: 30s

  - job_name: 'ollama'
    static_configs:
      - targets: ['localhost:11434']
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093
