# Prometheus configuration for Phoenix MLS Scraper monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: phoenix-mls-monitor
    service: phoenix-mls-scraper

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'phoenix_mls_scraper'
    
    # Override the global default and scrape targets more frequently
    scrape_interval: 10s
    scrape_timeout: 10s
    
    # Metrics path defaults to '/metrics'
    metrics_path: /metrics
    
    static_configs:
      - targets: ['localhost:9090']
        labels:
          environment: 'production'
          component: 'scraper'
          region: 'phoenix'
    
  # System metrics from node_exporter (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          environment: 'production'
          component: 'system'