# Secret Health Monitoring Alert Configuration
# This configuration defines alert rules for secret validation and health monitoring

groups:
  - name: secret-health-alerts
    rules:
      - alert: ProductionSecretsFailure
        expr: secret_validation_status{environment="production"} == 0
        for: 0m
        labels:
          severity: critical
          component: secrets
          environment: production
          alert_type: p0-incident
        annotations:
          summary: "Production secrets validation failed"
          description: "Critical production secrets are missing or invalid. System may be DOWN. Immediate action required."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/secret-validation-runbook.md"
          escalation: "P0 - Acknowledge within 15 minutes, resolve within 2 hours"
      
      - alert: TestSecretsFailure
        expr: secret_validation_status{environment="test"} == 0
        for: 5m
        labels:
          severity: warning
          component: secrets
          environment: test
          alert_type: p2-high
        annotations:
          summary: "Test environment secrets validation failed"
          description: "Test environment secrets are missing or invalid. Development workflows may be impacted."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/secret-validation-runbook.md"
          escalation: "P2 - Resolve within 24 hours"
      
      - alert: ServiceConnectivityFailure
        expr: service_connectivity_status{service=~"mongodb|maricopa_api"} == 0
        for: 2m
        labels:
          severity: critical
          component: connectivity
          service: "{{ $labels.service }}"
          alert_type: p0-incident
        annotations:
          summary: "Critical service {{ $labels.service }} unreachable"
          description: "Unable to connect to {{ $labels.service }}. Data collection and processing may be impacted."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/connectivity-troubleshooting.md"
          escalation: "P0 - Immediate investigation required"
      
      - alert: ProxyServiceDegraded
        expr: service_connectivity_status{service="webshare_proxy"} == 0
        for: 10m
        labels:
          severity: warning
          component: connectivity
          service: proxy
          alert_type: p2-high
        annotations:
          summary: "Proxy service degraded"
          description: "WebShare proxy service is unreachable. Scraping operations may be impacted but system can continue with reduced functionality."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/proxy-troubleshooting.md"
          escalation: "P2 - Monitor and resolve within 24 hours"
      
      - alert: SecretValidationStale
        expr: time() - secret_validation_last_success_timestamp > 86400
        for: 0m
        labels:
          severity: warning
          component: monitoring
          alert_type: p2-high
        annotations:
          summary: "Secret validation monitoring stale"
          description: "Secret validation workflow has not succeeded in over 24 hours. Monitoring system may have issues."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/monitoring-troubleshooting.md"
          escalation: "P2 - Investigate monitoring system health"
      
      - alert: DeadMansSwitchActivated
        expr: dead_mans_switch_critical_failures > 0
        for: 0m
        labels:
          severity: critical
          component: workflows
          alert_type: p0-incident
        annotations:
          summary: "Dead man's switch activated - Critical workflows failing"
          description: "{{ $value }} critical workflow(s) have stopped functioning. Potential production outage scenario."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/dead-mans-switch-runbook.md"
          escalation: "P0 - System may be DOWN. Immediate investigation required."
      
      - alert: WorkflowHealthDegraded
        expr: dead_mans_switch_warning_count > 0
        for: 15m
        labels:
          severity: warning
          component: workflows
          alert_type: p2-high
        annotations:
          summary: "Workflow health degraded"
          description: "{{ $value }} workflow(s) showing intermittent failures. Monitor for potential escalation."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/workflow-health-runbook.md"
          escalation: "P2 - Monitor and investigate within 4 hours"
      
      - alert: GitHubActionsQuotaHigh
        expr: github_actions_quota_usage_percent > 80
        for: 1h
        labels:
          severity: warning
          component: infrastructure
          alert_type: p2-high
        annotations:
          summary: "GitHub Actions quota usage high"
          description: "GitHub Actions quota usage at {{ $value }}%. Consider optimizing workflows or upgrading plan."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/quota-management.md"
          escalation: "P2 - Optimize usage or plan upgrade within 24 hours"
      
      - alert: BudgetThresholdExceeded
        expr: budget_usage_percent > 90
        for: 5m
        labels:
          severity: critical
          component: budget
          alert_type: p1-urgent
        annotations:
          summary: "Budget threshold exceeded"
          description: "Monthly budget usage at {{ $value }}%. Immediate cost review required."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/budget-management.md"
          escalation: "P1 - Review and optimize costs within 4 hours"

  - name: emergency-response-alerts
    rules:
      - alert: EmergencyResponseRequired
        expr: |
          (
            secret_validation_status{environment="production"} == 0
          ) or (
            dead_mans_switch_critical_failures > 0
          ) or (
            service_connectivity_status{service=~"mongodb|maricopa_api"} == 0
          )
        for: 0m
        labels:
          severity: critical
          component: emergency
          alert_type: p0-incident
          auto_response: enabled
        annotations:
          summary: "Emergency response automation triggered"
          description: "Critical system failure detected. Emergency response workflow will be automatically triggered."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/emergency-response-runbook.md"
          escalation: "P0 - Automated recovery initiated. Monitor and assist as needed."
          workflow_trigger: "emergency-response.yml"
      
      - alert: MultipleServiceFailures
        expr: |
          (
            count(service_connectivity_status == 0) > 1
          ) and (
            secret_validation_status{environment="production"} == 1
          )
        for: 5m
        labels:
          severity: critical
          component: services
          alert_type: p0-incident
        annotations:
          summary: "Multiple service connectivity failures"
          description: "Multiple critical services are unreachable despite valid secrets. Infrastructure or network issue likely."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/multi-service-failure-runbook.md"
          escalation: "P0 - Infrastructure investigation required immediately"
      
      - alert: SystemRecoverySuccess
        expr: |
          (
            secret_validation_status{environment="production"} == 1
          ) and (
            dead_mans_switch_critical_failures == 0
          ) and (
            count(service_connectivity_status == 0) == 0
          )
        for: 10m
        labels:
          severity: info
          component: recovery
          alert_type: recovery
        annotations:
          summary: "System recovery confirmed"
          description: "All critical systems have returned to healthy state. Recovery successful."
          runbook_url: "https://github.com/{{ github.repository }}/blob/main/docs/operations/recovery-verification.md"
          escalation: "INFO - Recovery complete. Continue monitoring."