name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Test input"
        required: false
        type: string
        default: "test"

jobs:
  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Echo test
      run: |
        echo "Workflow dispatch working"
