name: Validate Secrets

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to validate (test/production)'
        required: false
        default: 'production'
        type: string
    outputs:
      validation-status:
        description: 'Secret validation status'
        value: ${{ jobs.validate.outputs.status }}

jobs:
  validate:
    name: Validate Required Secrets
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
    
    steps:
    - name: Check Required Secrets
      id: check
      run: |
        missing_secrets=()
        
        # Check environment-specific secrets
        if [[ "${{ inputs.environment }}" == "test" ]]; then
          # Test environment secrets
          [[ -z "${{ secrets.TEST_MONGODB_PASSWORD }}" ]] && missing_secrets+=("TEST_MONGODB_PASSWORD")
          [[ -z "${{ secrets.TEST_MARICOPA_API_KEY }}" ]] && missing_secrets+=("TEST_MARICOPA_API_KEY")
          [[ -z "${{ secrets.TEST_WEBSHARE_API_KEY }}" ]] && missing_secrets+=("TEST_WEBSHARE_API_KEY")
          [[ -z "${{ secrets.TEST_CAPTCHA_API_KEY }}" ]] && missing_secrets+=("TEST_CAPTCHA_API_KEY")
        else
          # Production environment secrets
          [[ -z "${{ secrets.MONGODB_URL }}" ]] && missing_secrets+=("MONGODB_URL")
          [[ -z "${{ secrets.MARICOPA_API_KEY }}" ]] && missing_secrets+=("MARICOPA_API_KEY")
          [[ -z "${{ secrets.WEBSHARE_API_KEY }}" ]] && missing_secrets+=("WEBSHARE_API_KEY")
          [[ -z "${{ secrets.CAPTCHA_API_KEY }}" ]] && missing_secrets+=("CAPTCHA_API_KEY")
        fi
        
        # Check common secrets
        [[ -z "${{ secrets.GITHUB_TOKEN }}" ]] && missing_secrets+=("GITHUB_TOKEN")
        
        if [ ${#missing_secrets[@]} -eq 0 ]; then
          echo "✅ All required secrets are configured"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "❌ Missing required secrets:"
          printf '%s\n' "${missing_secrets[@]}"
          echo ""
          echo "Please configure these secrets in:"
          echo "Repository Settings → Secrets and variables → Actions"
          echo ""
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi
    
    - name: Validate Secret Formats
      if: success()
      run: |
        echo "🔍 Validating secret formats..."
        
        # Validate API key formats (basic checks)
        if [[ "${{ inputs.environment }}" == "test" ]]; then
          # Check test API keys aren't using default values
          if [[ "${{ secrets.TEST_MARICOPA_API_KEY }}" == "test-key" ]]; then
            echo "❌ TEST_MARICOPA_API_KEY is using default value"
            exit 1
          fi
          if [[ "${{ secrets.TEST_WEBSHARE_API_KEY }}" == "test-key" ]]; then
            echo "❌ TEST_WEBSHARE_API_KEY is using default value"
            exit 1
          fi
          if [[ "${{ secrets.TEST_CAPTCHA_API_KEY }}" == "test-key" ]]; then
            echo "❌ TEST_CAPTCHA_API_KEY is using default value"
            exit 1
          fi
        fi
        
        echo "✅ Secret format validation passed"