name: Workflow Test Minimal

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Test mode"
        required: false
        type: choice
        options: ["quick", "full"]
        default: "quick"

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Echo test
      run: |
        echo "Test mode: ${{ github.event.inputs.test_mode || \"quick\" }}"
        echo "Workflow test completed successfully"
